class SearchCity {
  Map<String, dynamic> cities = {
    'Pan India': [
      'Andaman and Nicobar Islands',
      'Andhra Pradesh',
      'Arunachal Pradesh',
      'Assam',
      'Bihar',
      'Chandigarh',
      'Chhattisgarh',
      'Dadra and Nagar Haveli',
      'Daman and Diu',
      'Delhi NCR',
      'Goa',
      'Gujarat',
      'Haryana',
      'Himachal Pradesh',
      'Jammu and Kashmir',
      'Jharkhand',
      'Karnataka',
      'Kerala',
      'Ladakh',
      'Lakshadweep',
      'Madhya Pradesh',
      'Maharashtra',
      'Manipur',
      'Meghalaya',
      'Mizoram',
      'Nagaland',
      'Odisha',
      'Puducherry',
      'Punjab',
      'Rajasthan',
      'Sikkim',
      'Tamil Nadu',
      'Telangana',
      'Tripura',
      'Uttar Pradesh',
      'Uttarakhand',
      'West Bengal'
    ],
    'Andaman and Nicobar Islands': ['North Middle Andaman', 'South Andaman'],
    'Andhra Pradesh': [
      'Anantapur',
      'Andhra Pradesh',
      'Chittoor',
      'Cuddapah',
      'East Godavari',
      'Guntur',
      'Hyderabad',
      'Kadapa',
      'Kakinada',
      'Krishna',
      'Kurnool',
      'Nellore',
      'Ongole',
      'Parwada, Viskhapatnam',
      'Prakasam',
      'Rajahmundry',
      'Sikar',
      'Srikakulam',
      'Tirupathi',
      'Vijayawada',
      'Vijayvada',
      'Vijaywada',
      'Visakhapatnam',
      'Vishakhapatnam',
      'Vizianagaram',
      'West Godavari'
    ],
    'Arunachal Pradesh': [
      'Changlang',
      'Dibang Valley',
      'East Kameng',
      'East Siang',
      'Kamle',
      'Kra Daadi',
      'Kurung Kumey',
      'Lepa Rada',
      'Lohit',
      'Longding',
      'Lower Dibang Valley',
      'Lower Siang',
      'Lower Subansiri',
      'Namsai',
      'Pakke Kessang',
      'Papum Pare',
      'Papumpare Dist',
      'Shi Yomi',
      'Siang',
      'Tawang',
      'Tirap',
      'Upper Siang',
      'Upper Subansiri',
      'West Kameng',
      'West Siang'
    ],
    'Assam': [
      'Assam',
      'Bajali',
      'Baksa',
      'Barpeta',
      'Beltola, Guwahati',
      'Biswanath',
      'Bongaigaon',
      'Cachar',
      'Charaideo',
      'Charieodeo',
      'Chirang',
      'Darrang',
      'Dhaligaon, Assam',
      'Dhemaji',
      'Dhubri',
      'Dibrugarh',
      'Dibrugarh, Tin- Sukia, Sivsagar',
      'Dibrugarh, Tinsukia, Sivsagar',
      'Dima Hasao',
      'Dimahasoe',
      'Goalpara',
      'Golaghat',
      'Guwahati',
      'Hailakandi',
      'Hojai',
      'Jorhat',
      'Kamrup',
      'Kamrup Metro',
      'Kamrup Metropolitan',
      'Karbi Anglong',
      'Karbianglong',
      'Karimganj',
      'Kheri',
      'Kokrajhar',
      'Lakhimpur',
      'Majuli',
      'Morigaon',
      'Nagaon',
      'Nalbari',
      'Nogoan',
      'North Lakhimpur',
      'Samaguri',
      'Samaguri,',
      'Saukuchi, Guwahati',
      'Sibsagar',
      'Silchar',
      'Silchar, Assam',
      'Sivasagar',
      'Sivsagar',
      'Sonitpur',
      'South Salmara-Mankachar',
      'Tinsukia',
      'Udalguri',
      'West Karbi Anglong'
    ],
    'Bihar': [
      'Araria',
      'Arwal',
      'Aurangabad',
      'Banka',
      'Barh',
      'Begusarai',
      'Bettiah',
      'Bhagalpur',
      'Bhagalpur District',
      'Bhojpur',
      'Bihar',
      'Buxar',
      'Chapra',
      'Dalsingsarai',
      'Darbhanga',
      'East Champaran',
      'Gaya',
      'Gaya District',
      'Gopalganj',
      'Gurugram',
      'Jamui',
      'Jehanabad',
      'Kaimur',
      'Katihar',
      'Khagaria',
      'Kishanganj',
      'Lakhi Bagh Darbhanga',
      'Lakhisarai',
      'Madhepura',
      'Madhubani',
      'Munger',
      'Muzaffarpur',
      'Nalanda',
      'Nawada',
      'Pan Bihar',
      'Patna',
      'Patna, Bihar',
      'Purnea',
      'Purnia',
      'Rohtas',
      'Saharsa',
      'Samastipur',
      'Saran',
      'Sheikhpura',
      'Sheohar',
      'Sitamarhi',
      'Siwan',
      'Supaul',
      'Vaishali',
      'West Champaran'
    ],
    'Chandigarh': [],
    'Chhattisgarh': [
      'Ambikapur',
      'Balod',
      'Baloda Bazar',
      'Balrampur Ramanujganj',
      'Bastar',
      'Bemetara',
      'Bhilai',
      'Bijapur',
      'Bilaspur',
      'Dantewada',
      'Dhamtari',
      'Dur',
      'Durg',
      'Durg Bhilai',
      'Durg-Bhilai',
      'Gariaband',
      'Gaurela Pendra Marwahi',
      'Jagdalpur',
      'Janjgir Champa',
      'Jashpur',
      'Kabirdham',
      'Kanker',
      'Kharsia',
      'Kondagaon',
      'Korba',
      'Koriya',
      'Mahasamund',
      'Mungeli',
      'Naila',
      'Narayanpur',
      'Raigarh',
      'Raipur',
      'Rajnandgaon',
      'Sukma',
      'Surajpur',
      'Surguja'
    ],
    'Dadra and Nagar Haveli': [],
    'Daman and Diu': [],
    'Delhi NCR': [
      'Central Delhi',
      'Delhi',
      'Delhi Ncr',
      'East Delhi',
      'Faridabad',
      'Ghaziabad',
      'Greater Noida',
      'Gurgaon',
      'New Delhi',
      'New Delhi',
      'Noida',
      'North Delhi',
      'North Delhi',
      'North East Delhi',
      'North West Delhi',
      'South Delhi',
      'South East Delhi',
      'South West Delhi',
      'West Delhi'
    ],
    'Goa': ['Margao', 'North Goa', 'Salcete', 'South Goa'],
    'Gujarat': [
      'Ahemdabad',
      'Ahmedabad',
      'Amreli',
      'Anand',
      'Aravalli',
      'Bahod',
      'Banaskantha',
      'Bardoli',
      'Baroda',
      'Bharuch',
      'Bhavnagar',
      'Bhuj',
      'Bijapur',
      'Bilimora',
      'Botad',
      'Chhota Udaipur',
      'Dadra And Nagar Haveli',
      'Dadra Und Nagar Hav.',
      'Dadra Und Nagar Hav.',
      'Dahod',
      'Dang',
      'Deesa',
      'Devbhoomi Dwarka',
      'Dhanera',
      'Dhoraji',
      'Gandhidham',
      'Gandhinagar',
      'Gir Somnath',
      'Godhra',
      'Gondal',
      'Gujarat',
      'Himatnagar',
      'Idar',
      'Jamkhambalia',
      'Jamnagar',
      'Junagadh',
      'Junagarh',
      'Kadi',
      'Kalol',
      'Keshod',
      'Khambhat',
      'Kheda',
      'Kutch',
      'Mahesana',
      'Mahisagar',
      'Mehsana',
      'Modasa',
      'Morbi',
      'Nadiad',
      'Narmada',
      'Navsari',
      'Palanpur',
      'Panchmahal',
      'Patan',
      'Porbandar',
      'Rajkot',
      'Sabarkantha',
      'Siddpur',
      'Surat',
      'Surendranagar',
      'Tapi',
      'Ulhas Nagar',
      'Una',
      'Unjha',
      'Vadodara',
      'Valsad',
      'Vapi',
      'Veraval',
      'Vijapur',
      'Viramgam',
      'Visnagar',
      'Vyara'
    ],
    'Haryana': [
      'Ahead Of Faridabad',
      'Ambala',
      'Ambala, Hary- Ana',
      'Bawal, Rewari',
      'Bhiwani',
      'Charkhi Dadri',
      'Dwarka Delhi',
      'Faridabad',
      'Fatehabad',
      'Gurgaon',
      'Gurgaon Manesar',
      'Gurugram',
      'Gurugram, Haryana',
      'Gurugram, Manesar',
      'Hisar',
      'Hisar, Haryana',
      'Jhajjar',
      'Jind',
      'Kaithal',
      'Karnai',
      'Karnal',
      'Kurukshetra',
      'Mahendragarh',
      'Manesar',
      'Manesar, Gurgaon',
      'Mewat',
      'Narnaul',
      'Nub',
      'Palwal',
      'Panchkula',
      'Panipat',
      'Panipat, Hary- Ana',
      'Plot 324 Sector 7, Manesar, Haryana',
      'Rewari',
      'Rohtak',
      'Sirsa',
      'Sisar',
      'Sonepat',
      'Sonepat Hary- Ana',
      'Sonipat',
      'Yamuna Nagar',
      'Yamuna Nagar, Haryana',
      'Yamunanagar'
    ],
    'Himachal Pradesh': [
      'Bilaspur',
      'Chamba',
      'Hamirpur',
      'Kangra',
      'Kinnaur',
      'Kullu',
      'Lahaul Spiti',
      'Mandi',
      'Shimla',
      'Sirmaur',
      'Solan',
      'Una'
    ],
    'Jammu and Kashmir': [
      'Bandipora',
      'Baramulla',
      'Budgam',
      'Doda',
      'Ganderbal',
      'Jammu',
      'Kashmir',
      'Kasmir, Lal Bazar Srinagar',
      'Kathua',
      'Kishtwar',
      'Kulgam',
      'Kupwara',
      'Poonch',
      'Pulwama',
      'Rajouri',
      'Ramban',
      'Reasi',
      'Samba',
      'Samba, Jammu',
      'Shopian',
      'Srinagar',
      'Udhampur'
    ],
    'Jharkhand': [
      'Bokaro',
      'Chatra',
      'Deoghar',
      'Dhanbad',
      'Dumka',
      'East Singhbhum',
      'Garhwa',
      'Giridih',
      'Godda',
      'Gumla',
      'Hazaribagh',
      'Jamshedpur',
      'Jamtara',
      'Jharkhand',
      'Khunti',
      'Koderma',
      'Latehar',
      'Lohardaga',
      'Pakur',
      'Palamu',
      'Ramgarh',
      'Ranchi',
      'Sahebganj',
      'Seraikela Kharsawan',
      'Simdega',
      'West Singhbhum'
    ],
    'Karnataka': [
      'Aluva',
      'Ananthapur',
      'Bagalkot',
      'Bali/Belur',
      'Bangalore',
      'Bangalore Kerala',
      'Belgaum',
      'Bellary',
      'Belur',
      'Bengaluru',
      'Bidadi',
      'Bidar',
      'Bijapur',
      'Bismillah Nagar, Bangalore',
      'Chamarajanagar',
      'Chickballapur',
      'Chikkaballapur',
      'Chikkamagaluru',
      'Chitradurga',
      'Cuddapah',
      'Dakshina Kannada',
      'Davanagere',
      'Dharwad',
      'Ernakulam',
      'Gadag',
      'Gowripalya',
      'Gowripalya Mysore Road',
      'Gulbarga',
      'Hassan',
      'Haveri',
      'Hubli',
      'Kadappa',
      'Kodagu',
      'Kolar',
      'Koppal',
      'Kovalur, Nellore',
      'Mandya',
      'Mangalore',
      'Mangalore/ Hassan',
      'Mysore',
      'Nellore',
      'Raichur',
      'Ramanagara',
      'Shimoga',
      'Tumkur',
      'Udupi',
      'Uttara Kannada',
      'Vijayanagara',
      'Vijayapura',
      'Whitefield',
      'Yadgir'
    ],
    'Kerala': [
      'Alappuzha',
      'Alwaye',
      'Attingal',
      'Calicut',
      'Calicut/ Malapprum',
      'Cannanore',
      'Cochin',
      'Cochin And Other Parts Of Kerala',
      'Ernakulam',
      'Idukki',
      'Kannur',
      'Kasaragod',
      'Kasargod',
      'Kollam',
      'Kottayam',
      'Kozhikode',
      'Malappuram',
      'Palakkad',
      'Pathanamthitta',
      'Thiruvalla',
      'Thiruvananthapuram',
      'Thrissur',
      'Trichur',
      'Trivandrum',
      'Wayanad'
    ],
    'Ladakh': ['Leh'],
    'Lakshadweep': [],
    'Madhya Pradesh': [
      'Agar Malwa',
      'Agra',
      'Alirajpur',
      'Anuppur',
      'Ashoknagar',
      'Balaghat',
      'Barwani',
      'Betul',
      'Bhind',
      'Bhopal',
      'Biaora',
      'Burhanpur',
      'Chachaura',
      'Chhatarpur',
      'Chhatarpur (M.P)',
      'Chhindwara',
      'Damoh',
      'Datia',
      'Dewas',
      'Dhar',
      'Dindori',
      'Guna',
      'Gwalior',
      'Harda',
      'Hatpipliya',
      'Hoshangabad',
      'Indore',
      'Indore, Kashla Gate',
      'Indore/Bhopal',
      'Itarsi',
      'Jabalpur',
      'Jhabua',
      'Katni',
      'Khandwa',
      'Khargone',
      'Lucknow',
      'Madhya Pradesh',
      'Maihar',
      'Mandla',
      'Mandsaur',
      'Mhow',
      'Morena',
      'Mumbai',
      'Nagda',
      'Narsinghpur',
      'Neemuch',
      'Niwari',
      'Panna',
      'Pipariya',
      'Pipariya ,Hoshangabad(Mp)',
      'Pipariya(Hoshangabad)',
      'Raisen',
      'Rajgarh',
      'Ratlam',
      'Rewa',
      'Sagar',
      'Satna',
      'Sehore',
      'Seoni',
      'Shahdol',
      'Shajapur',
      'Sheopur',
      'Shivpuri',
      'Sidhi',
      'Singrauli',
      'Thane',
      'Tikamgarh',
      'Ujjain',
      'Umaria',
      'Vidisha',
      'Waidhan P. O.'
    ],
    'Maharashtra': [
      'Ahmednagar',
      'Airoli, Navi Mumbai',
      'Akkalkot',
      'Akluj',
      'Akola',
      'Alibag',
      'All Over Maharashtra',
      'Amarvati',
      'Ambejogai',
      'Amgaon',
      'Amravati',
      'Andheri To Mulund',
      'Aurangabad',
      'Aurangpura',
      'Aurngabad',
      'Baramati',
      'Barshi',
      'Basmat',
      'Beed',
      'Bhandara',
      'Bhandup',
      'Bhayander',
      'Bhiwandi',
      'Bhiwandi, Mum- Bai',
      'Bhor',
      'Bhusawal',
      'Buldana',
      'Buldhana',
      'Byculla',
      'Chakan, Pune',
      'Chalisgaon',
      'Chalkaranji',
      'Chandrapur',
      'Chinchwad',
      'Chiplun',
      'Dahisar',
      'Deulgaon Raja',
      'Dharavi',
      'Dhule',
      'Dhulia',
      'Dombivili',
      'Dondicha',
      'Gadchiroli',
      'Gadhinglaj',
      'Gangakhed',
      'Gatkopar,Mumbai',
      'Ghatkopar East, Mumbai',
      'Gondia',
      'Govandi, Mumbai',
      'Hingoli',
      'Icchalkaranji',
      'Ichalkaranji',
      'Jalgaon',
      'Jalna',
      'Jejuri/ Satara/ Kolhapur',
      'Kalamb',
      'Kalyan',
      'Kamptee',
      'Kankawali',
      'Karad',
      'Karmala',
      'Kedgaon',
      'Khamgaon',
      'Kharghar',
      'Khopoli',
      'Kolhapur',
      'Latur',
      'Loha',
      'Mahad',
      'Maharashtra',
      'Malegaon',
      'Malkapur',
      'Manchar',
      'Miraj',
      'Mulund, Mumbai',
      'Mumbai',
      'Mumbai (Bhandup, Nahur, Mulund, Kanjurmarg)',
      'Mumbai, Bandra',
      'Mumbai, Navi Mumbai And Pune',
      'Mumbai, Navi Mumbai, Pune',
      'Mumbai/Pune',
      'Mumbai/Rabale',
      'Nagpur',
      'Nanded',
      'Nandurbar',
      'Narayangaon',
      'Nashik',
      'Navi Mumbai',
      'Navi Mumbai, Airoli',
      'Navi Mumbai',
      'Nehru Place',
      'Omerga',
      'Osmanabad',
      'Palghar',
      'Pandharpur',
      'Panvel',
      'Parali Vajinath',
      'Parbhani',
      'Phaltan',
      'Pimpri',
      'Pimpri Chinchwad',
      'Pune',
      'Pune , Mumbai',
      'Pune And Mumbai',
      'Pune/Mumbai',
      'Pusad',
      'Rabale, Navi Mumbai',
      'Raigad',
      'Rajapur',
      'Ratnagiri',
      'Sangamner',
      'Sangli',
      'Sangola',
      'Satara',
      'Satpur, Nashik',
      'Shirampur',
      'Shirampur, Mahrashtra',
      'Shirur',
      'Sholapur',
      'Sillod',
      'Sindhudurg',
      'Sinner',
      'Sinner, Nashik',
      'Solapur',
      'Tarapur',
      'Thane',
      'Thane, Mumbai',
      'Thergaon Pune',
      'Udgir',
      'Uran Islampur, Sangli',
      'Valsad',
      'Vasai',
      'Vashi',
      'Vishrantwadi, Pune',
      'Vita',
      'Wada',
      'Wadala',
      'Wai',
      'Wardha',
      'Washim',
      'Yavatmal'
    ],
    'Manipur': [
      'Chandel',
      'Churachandpur',
      'Imphal',
      'Imphal East',
      'Imphal West',
      'Jiribam',
      'Kakching',
      'Kamjong',
      'Kangpokpi',
      'Noney',
      'Pherzawl',
      'Senapati',
      'Tamenglong',
      'Tengnoupal',
      'Thoubal',
      'Ukhrul'
    ],
    'Meghalaya': [
      'East Garo Hills',
      'East Jaintia Hills',
      'East Khasi Hills',
      'Meghalaya',
      'Meghalaya And Assam',
      'North Garo Hills',
      'Ri Bhoi',
      'Shillong',
      'South Garo Hills',
      'South West Garo Hills',
      'South West Khasi Hills',
      'West Garo Hills',
      'West Jaintia Hills',
      'West Khasi Hills'
    ],
    'Mizoram': [
      'Champhai',
      'Hnahthial',
      'Khawzawl',
      'Kolasib',
      'Lawngtlai',
      'Lunglei',
      'Mamit',
      'Mizoram',
      'Saiha',
      'Saitual',
      'Serchhip'
    ],
    'Nagaland': [
      'Dimapur, Naga- Land',
      'Kiphire',
      'Kohima',
      'Longleng',
      'Mokokchung',
      'Mon',
      'Noklak',
      'Peren',
      'Phek',
      'Tuensang',
      'Wokha',
      'Zunheboto'
    ],
    'Odisha': [
      'Angul',
      'Balangir',
      'Balasore',
      'Bargarh',
      'Bhadrak',
      'Bhubaneswar',
      'Boudh',
      'Cuttack',
      'Debagarh',
      'Dhenkanal',
      'Gajapati',
      'Ganjam',
      'Jagatsinghpur',
      'Jajpur',
      'Jharsuguda',
      'Kalahandi',
      'Kandhamal',
      'Kendrapara',
      'Kendujhar',
      'Khordha',
      'Koraput',
      'Malkangiri',
      'Mayurbhanj',
      'Nabarangpur',
      'Nayagarh',
      'Nuapada',
      'Orissa',
      'Puri',
      'Rayagada',
      'Sambalpur',
      'Sambalpur Dist',
      'Subarnapur',
      'Sundergarh'
    ],
    'Puducherry': ['Mahe', 'Puducherry', 'Yanam'],
    'Punjab': [
      'Ambala',
      'Ambala City',
      'Amritsar',
      'Barnala',
      'Bathinda',
      'Bathinda Punjab',
      'Chandigarh',
      'Derrabassi',
      'Derrabassi, Punjab',
      'Faridkot',
      'Fatehgarh Sahib',
      'Fazilka',
      'Firozpur',
      'Gurdaspur',
      'Hoshiarpur',
      'Jalandhar',
      'Kapurthala',
      'Khanna',
      'Ludhiana',
      'Mansa',
      'Moga',
      'Mohali',
      'Muktsar',
      'Pathankot',
      'Patiala',
      'Rajpura',
      'Rupnagar',
      'Sangrur',
      'Shaheed Bhagat Singh Nagar',
      'Tarn Taran',
      'Zirakpur'
    ],
    'Rajasthan': [
      'Ajmer',
      'Alwar',
      'Banswara',
      'Baran',
      'Barmer',
      'Bharatpur',
      'Bhilwara',
      'Bhiwadi',
      'Bikaner',
      'Bundi',
      'Chittorgarh',
      'Churu',
      'Dausa',
      'Dholpur',
      'Dungarpur',
      'Hanumangarh',
      'Jaipur',
      'Jaipur I',
      'Jaipur Ii',
      'Jaipur/Kota',
      'Jaisalmer',
      'Jalore',
      'Jhalawar',
      'Jhunjhunu',
      'Jhunjhunuu',
      'Jodhpur',
      'Karauli',
      'Kota',
      'Kotputli',
      'Nagaur',
      'Pali',
      'Pratapgarh',
      'Rajasthan',
      'Rajkot',
      'Rajsamand',
      'Ringus, Sikar',
      'S. Madhopur',
      'Sagwara',
      'Sawai Madhopur',
      'Sheoganj',
      'Sikar',
      'Sirohi',
      'Sri Ganganagar',
      'Tonk',
      'Udaipur'
    ],
    'Sikkim': ['North Sikkim', 'South Sikkim', 'West Sikkim'],
    'Tamil Nadu': [
      'Ariyalur',
      'Chengalpattu',
      'Chennai',
      'Chennai / Trichy',
      'Coimbatore',
      "Coimbatore'",
      'Coimbatore/ Trichy',
      'Cuddalore',
      'Dharampri/ Krishnapuri',
      'Dharmapuri',
      'Dindigul',
      'Dindugal',
      'Erode',
      'Kallakurichi',
      'Kanchipuram',
      'Kanyakumari',
      'Karur',
      'Krishna',
      'Krishnagiri',
      'Krishnagiti',
      'Madurai',
      'Malappuram',
      'Mayiladuthurai',
      'Nagapattinam',
      'Nagercoil',
      'Namakkal',
      'Nilgiris',
      'Pathanamthitta',
      'Perambalur',
      'Pondicherry',
      'Puducherry',
      'Pudukkottai',
      'Ramanathapuram',
      'Ranipet',
      'Salem',
      'Sivaganga',
      'Tamil Nadu',
      'Tanjore',
      'Tenkasi',
      'Thanjavur',
      'Theni',
      'Thoothukudi',
      'Thrissur',
      'Tiruchirappalli',
      'Tirunelveli',
      'Tirupattur',
      'Tiruppur',
      'Tiruvallur',
      'Tiruvannamalai',
      'Tiruvarur',
      'Trichur',
      'Trichy',
      'Tuirrupur',
      'Tuticorin',
      'Vellore',
      'Viluppuram',
      'Virudhunagar'
    ],
    'Telangana': [
      'Adilabad',
      'Bachupally',
      'Bhadradri Kothagudem',
      'Chevella',
      'Cyberabad',
      'Delhi',
      'Fasalwadi',
      'Ghanpur',
      'Greater Hyderabad Municipal Corporation',
      'Himayatsagar',
      'Hyderabad',
      'Hyerabad',
      'Jadchelra, Near Hyderabad',
      'Jagtial',
      'Jangaon',
      'Jayashankar Bhupalpally',
      'Jogulamba Gadwal',
      'Kamareddy',
      'Kanchanbagh',
      'Karimnagar',
      'Karimnagar,',
      'Khammam',
      'Komaram Bheem',
      'Kothagudem',
      'Lb Nagar',
      'Mahabubabad',
      'Mahabubnagar',
      'Mahbubnagar',
      'Malkajgiri',
      'Mancherial',
      'Maredpally',
      'Medak',
      'Medchal',
      'Moinabad',
      'Mulugu',
      'Nagarkurnool',
      'Nalgonda',
      'Narayanpet',
      'Nirmal',
      'Nizamabad',
      'Peddapalli',
      'Rajanna Sircilla',
      'Ranga Reddy',
      'Rangareddy',
      'Sangareddy',
      'Secunderabad',
      'Siddipet',
      'Sircilla',
      'Sripuram',
      'Suraram',
      'Suryapet',
      'Telangana',
      'Vikarabad',
      'Wanaparthy',
      'Warangal',
      'Warangal Rural',
      'Warangal Urban',
      'Yadadri Bhuvanagiri'
    ],
    'Tripura': [
      'Dhalai',
      'Gomati',
      'Khowai',
      'North Tripura',
      'Sepahijala',
      'South Tripura',
      'Tripura',
      'Unakoti',
      'West Tripura'
    ],
    'Uttar Pradesh': [
      'Agra',
      'Aligarh',
      'Allahabad',
      'Ambedkar Nagar',
      'Amethi',
      'Amroha',
      'Auraiya',
      'Ayodhya',
      'Azamgarh',
      'Baghpat',
      'Bahraich',
      'Ballia',
      'Balrampur',
      'Banda',
      'Barabanki',
      'Bareilly',
      'Bareli',
      'Basti',
      'Benares',
      'Bhadohi',
      'Bhoothnath, Lucknow',
      'Bijnor',
      'Budaun',
      'Bulandshahr',
      'Chandauli',
      'Chitrakoot',
      'Dada Nagar Industrial Area, Kanpur',
      'Delhi Road, Meerut',
      'Deoria',
      'Etah',
      'Etawah',
      'F36 Sec 9, Noida',
      'Farrukhabad',
      'Fatehpur',
      'Firozabad',
      'G36, Sec-9, Noida',
      'Gautam Buddha Nagar',
      'Ghaziabad',
      'Ghaziabad, Vasundhara',
      'Ghazipur',
      'Gonda',
      'Gorakhpur',
      'Hamirpur',
      'Hamirpur,Up',
      'Hapur',
      'Hardoi',
      'Hathras',
      'Hyderabad',
      'Jalaun',
      'Jaunpur',
      'Jhansi',
      'Kannauj',
      'Kanpur',
      'Kanpur Dehat',
      'Kanpur Nagar',
      'Kasganj',
      'Kaushambi',
      'Kheri',
      'Kushinagar',
      'Lakhimpur Kheri',
      'Lalitpur',
      'Lucknow',
      'Lucknow Chinhat, Sitapur Road',
      'Lucknow. Chatameel Near Bhitauli',
      'Maharajganj',
      'Mahoba',
      'Mainpuri',
      'Mathura',
      'Mau',
      'Meerut',
      'Mirzapur',
      'Moradabad',
      'Muzaffar Nagar',
      'Muzaffarnagar',
      'Nagpur',
      'Noida',
      'Noida Delhi Ncr',
      'Noida Extension',
      'Pilibhit',
      'Pratapgarh',
      'Prayagraj',
      'Raebareli',
      'Rampur',
      'Saharanpur',
      'Sambhal',
      'Sant Kabir Nagar',
      'Sant Kabir Nagar,Basti',
      'Sec 78 Noida',
      'Sector 12 Noida Baarat Ghar',
      'Shahjahanpur',
      'Shamli',
      'Shikohabad',
      'Shravasti',
      'Shrawasti',
      'Siddharth Nagar',
      'Siddharthnagar',
      'Sitapur',
      'Sonbhadra',
      'Sultanpur',
      'Unnao',
      'Uttar Pradesh',
      'Varanasi'
    ],
    'Uttarakhand': [
      'Almora',
      'Bageshwar',
      'Chamoli',
      'Champawat',
      'Dehradun',
      'Dehradun, Uttarakhand',
      'Gurugram',
      'Haldwani',
      'Haridwar',
      'Jwalapur',
      'Nainital',
      'Pauri',
      'Pithoragarh',
      'Rishikesh',
      'Rudraprayag',
      'Tehri',
      'Udham Singh Nagar',
      'Uttarkashi'
    ],
    'West Bengal': [
      'Alipurduar',
      'Bankura',
      'Birbhum',
      'Chandannagar',
      'Chandannagar, West Bengal',
      'Chuchura',
      'Chuchura, West Bengal',
      'Cooch Behar',
      'Dakshin Dinajpur',
      'Darjeeling',
      'Durgapur',
      'Durgapur - West Bengal',
      'Hooghly',
      'Howrah',
      'Jalpaiguri',
      'Jhargram',
      'Kalimpong',
      'Kharagpur',
      'Kharagpur, West Bangal',
      'Khardah',
      'Kolkata',
      'Malda',
      'Murshidabad',
      'Nadia',
      'North 24 Parganas',
      'Paschim Bardhaman',
      'Paschim Medinipur',
      'Purba Bardhaman',
      'Purba Medinipur',
      'Purulia',
      'Siliguri',
      'South 24 Parganas',
      'South Kolkata',
      'Uttar Dinajpur',
      'West Bengal'
    ]
  };

  String search(String city) {
    String state;
    cities.forEach((key, value) {
      if (value == city) {
        state = key;
        return;
      }
    });
    return state;
  }

  List<String> selectCity(String state) {
    print(cities['$state']);
    return cities['$state'];
  }
}
